# Relationship Table

This table defines a mathematical function for each endogenous variable in the VAST model. Each function specifies how the variable is determined by its predecessors, following Schönbrodt’s (2023) formalization steps and Gagné et al.'s (2022) theoretical descriptions. Parameters are uniquely labeled to ensure semantic clarity and modular simulation.

| Target Variable                  | Predictor(s)                                            | Formula                                 | Free Parameter(s)                | Constraint(s)            | Justification |
|----------------------------------|----------------------------------------------------------|------------------------------------------|----------------------------------|--------------------------|---------------|
| CONTEXTUAL_COMPETENCE_THREATS   | REMOTE_WORK_CONTEXT                                     | T = β_T × remote                         | β_T ∈ [0, 1]                      | T ∈ [0, 1]               | Remote exposure generates risk for competence disruptions (Gagné, 2022, p. 14) |
| SOCIAL_DISCONNECTION_RISK       | REMOTE_WORK_CONTEXT                                     | D = δ_D × remote                         | δ_D ∈ [0, 1]                      | D ∈ [0, 1]               | Disconnection risk increases proportionally with remoteness (Gagné, 2022, p. 15) |
| AUTONOMY_SUPPORT_IN_REMOTE_WORK | REMOTE_WORK_CONTEXT                                     | A_supp = β_A × remote                    | β_A ∈ [0, 1]                      | A_supp ∈ [0, 1]          | Design quality activated under remote conditions (Gagné, 2022, p. 15) |
| NEED_SATISFACTION_AUTONOMY      | HYBRID_WORK_CONTEXT, AUTONOMY_SUPPORT_IN_REMOTE_WORK    | A = α_H × hybrid + γ_A × A_supp          | α_H, γ_A ∈ [0, 1]                 | A ∈ [0, 1]               | Hybrid and autonomy-supportive remote work both promote autonomy (Gagné, 2022, p. 15) |
| NEED_SATISFACTION_COMPETENCE    | CONTEXTUAL_COMPETENCE_THREATS                           | C = 1 – β_C × T                          | β_C ∈ [0, 1]                      | C ∈ [0, 1]               | Threats reduce competence linearly (Gagné, 2022, p. 14) |
| NEED_SATISFACTION_RELATEDNESS   | SOCIAL_DISCONNECTION_RISK                               | R = 1 – δ_R × D                          | δ_R ∈ [0, 1]                      | R ∈ [0, 1]               | Disconnection reduces relatedness linearly (Gagné, 2022, p. 15) |
| INTRINSIC_MOTIVATION            | AUTONOMY, COMPETENCE, RELATEDNESS                       | M = w₁ × A + w₂ × C + w₃ × R             | w₁, w₂, w₃ ∈ [0, 1]               | w₁ + w₂ + w₃ = 1         | Additive contributions of SDT needs (Deci & Ryan, 2000; Gagné, 2022, p. 7) |
| JOB_SATISFACTION                | INTRINSIC_MOTIVATION                                    | S = θ × M                                | θ ∈ [0, 1]                        | S ∈ [–1, 1]              | Reasoning link from motivation to satisfaction (Gagné, 2022, p. 7) |
